### PR TITLE
Add patch-state-change event and log

### PR DESCRIPTION
**Pull request by joselamego**
Add the patch-state-change event and corresponding log to API. Update documentation accordingly and add unit test.
As requested in issue #140

### CODE REVIEW

**Comment by dlespiau** [comment]
This looks much more in line (and simpler!). One one high level remark left: I think we need to change where he patch id is stored. It needs to be in the EventLog model, not in the parameters.

The reason is very simple, we'll need to be able to query the logs for events on patches, so the patch id has to be part of fields that can be easily queried. For instance to show the history of a patch: "give the list of state changes (ie all the EventLogs corresponding to the state change event) so I can display the history for this patch".

That means event logs will have a (series, patch) tuple to reference the object they are applied to.
- (series, None) for series level events
- (series, patch) for patch level events

I'll need to run the tests as well to make sure we don't regress, because I haven't yet hooked the CI system running tests to github pull requests. I think I'll migrate that system to travis soon-ish.

**Comment by joselamego** [comment]
Damien, I've moved the patch field from parameters and created the related migration. Let me know your thoughts.
Regards

**Comment by dlespiau** [comment]
Just rebased the pull request on master and it does pass the tests. There are still a few last things I'd like to check before merging (trivial PEP8 issues), but this looks good I think.

**Comment by dlespiau** [comment]
Took another closer look today:
- The biggest problem remaining was that your code to retrieve the series from the patch didn't work for anything else than series with 1 patch. I changed the test to reflect the problem and changed the way you retrieve the series from a patch object.
- Fixed some PEP8 warnings. Patchwork is now passing PEP8 tests and so should all the incoming pull requests. I moved my CI stuff to travis so pull requests can be tested automatically in the future.
- Lots of small things:
  - No CamelCase file name,
  - reorder the patches to make sense (the rule is, each patch should result in a working state for the project). For instance you can't have a commit that adds the ThreadLocalRequest middleware in the settings before the commit introducing that middleware class.
  - don't use super long lines in the documentation
  - Add "patch: null" to the series-new-revision event in the documentation
  - Other small things I didn't note :)

With all that fixed, merged you work. Thanks for the patches!

**Comment by joselamego** [comment]
Cool! Thanks for the extra work Damien.

**Comment by dlespiau** [comment]
No problem!

I've also pushed server-side filtering of the kind of events we can poll
with git poll-events, (eg. git poll-events --name=series-new-revision) so
the user doesn't have to retrieve all kinds of events.

**Pull request closed without merging**
