### PR TITLE
Consolidated pull request

### PR DESCRIPTION
**Pull request by joselamego**
When a new revision for a patch is received in Patchwork, the
earlier patch remains in New state, without any mention
that there is a newer revision unless a manual update is performed,
resulting in wrong metrics and UX.
With this change, after any Series with two or more revisions is
completed, a search in previous revision is performed, for patches
with same name as the latest, to mark them as Superseded and add a
comment with the update reason.

This implements [Issue #61]

Signed-off-by: Jose Lamego jose.a.lamego@linux.intel.com

### CODE REVIEW

**Comment by dlespiau** [comment]
well, at the very least the tests need to pass :)

**Comment by joselamego** [comment]
@dlespiau: please take a look at this change when you have the time, it does pass the tests now :)

**Comment by dlespiau** [comment]
Failing the tests again :/

Don't forget to use git history rewriting facilities to have a nice clean series (or rebase -i and/or git commit --fixup, etc...)

I'm away on holiday, so problabl can't review until August.

**Comment by joselamego** [comment]
The issue that caused CI tests to fail is fixed in #199

**Pull request closed without merging**
