### PR TITLE
parsemail: Update user's name to the last one used

### PR DESCRIPTION
**Pull request by ivyl**
Currently the first email patchwork picks up from an address defines
name assigned to that address. If it contains a typo it will stick and
require an admin to fix that.

Follow up mail with the name fixed does not change a thing.

Since the mboxes are recomposed using that name, the typo can stick to
multiple patches unnoticed, which seems to be the case quite often.

So let's fix that with updating Person with the latest name they used
from their email address.

Signed-off-by: Arkadiusz Hiler <arkadiusz.hiler@intel.com>

### CODE REVIEW

**Comment by ivyl** [comment]
I haven't run the tests as there seem to be components missing in requirements, but lets put it here so we won't lose track of it.

**Comment by dlespiau** [comment]
The idea looks sane to me, it would be excellent if you could add a unit test to it to verify it works. Have you tested it in any fashion?

The tests are failing indeed, it's has been a *very* long time since they were last ben run. I tried to freeze things as much as possible so tests pass in the future, but appeared to have missed something to get that import error on Django. Would be nice to fix the Travis run, but that can be a different PR.

**Comment by dlespiau** [comment]
An interesting difference between the successful test run in master and this PR is that `tox` has moved along from 2.3.1 to 2.7. I've seen `tox` break builds in the past.

**Comment by ivyl** [comment]
It was debug-toolbar breaking on the version of django used.  I'll update PR soon, adding tests and couple of commits fixing other issues. Thanks.

**Comment by ivyl** [comment]
Now only two tests fail due to selenium's geckodriver binary not being in the PATH. Possibly travis requires some configuration changes to add the dependency. Can you look into that? You probably will come up with the solution faster as I don't have any experience with this CI yet.

**Comment by dlespiau** [comment]
I'll try and see if I remember anything about it :)

**Comment by dlespiau** [comment]
With this commit https://github.com/dlespiau/patchwork/commit/f9041a0d284c00dca79d8ff030bb59d062152a0a, I'm going a bit further but the test to ensure the user name text entry is focused on the login page seems to fail. There's no real reason this should have changed, and ran a bit out of time I can use tracking it down today.

**Comment by ivyl** [comment]
That's odd. All the tests pass for me using chromedriver just fine, but on geckodriver I also have one of the tests failing:

```
======================================================================
ERROR: test_default_focus (patchwork.tests.test_user_browser.LoginTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/stash/src/patchwork/patchwork/tests/test_user_browser.py", line 32, in test_default_focus
    self.wait_until_focused('#id_username')
  File "/mnt/stash/src/patchwork/patchwork/tests/browser.py", line 157, in wait_until_focused
    Wait(self.selenium).until(is_focused, msg)
  File "/mnt/stash/src/patchwork/patchwork/tests/browser.py", line 62, in until
    raise TimeoutException(message)
TimeoutException: Message: The element matching '#id_username' should be focused
```

So I have run it in headed mode to see that for my self and surprisingly - the field IS focused and test still fails. I think it may be a FF/driver issue.

**Comment by dlespiau** [comment]
Right, we could just switch travis to use chrome/chromedriver instead, will try to find time to look at that today.

**Comment by ivyl** [comment]
Hey,

I managed to run a local copy of the patchwork just fine, so I'll have a solid base for manual testing / debugging.

I'll try to check what is wrong with the geckodriver / give a try switching travis to chromedriver on my fork later this week if you won't beat me to it :-)

Thanks!

**Comment by dlespiau** [comment]
Thank you! that would help tremendously, time to spend on patchwork is basically 0 these days.

**Comment by ivyl** [comment]
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/firefox/webdriver.py#L137
https://github.com/SeleniumHQ/selenium/blob/master/py/selenium/webdriver/remote/switch_to.py#L34

This was causing the inconsistency between Chrome and Firefox. I've workarounded that for now on our site. I may try fixing Selenium itself as my weekend project in the future :-)

**Comment by dlespiau** [comment]
Looks good, merging! thanks for fixing the tests as well, it makes it easier (possible?) to press the merge button.

**Pull request merged**
