### PR TITLE
Dev apitoken

### PR DESCRIPTION
**Pull request by dmgciubotaru**

### CODE REVIEW

**Comment by dlespiau** [comment]
This work introduces 128 new pep8 warnings. We currently have ~280 pep8 warnings, adding 50% with just this patch is not an option, so I'll have to fix that before going further. Or maybe you have time to do it?

```
$ (on master) tox -e pep8  > pep8.master
$ (dev-apitoken) tox -e pep8  > pep8.token
$ env)damien@strange:patchwork (20160301-token.2 %)
$ diff -u pep8.master pep8.token  | grep ^+ | wc -l
128
```

**Comment by cburlacu** [comment]
Here you have pep8 warnings fixed 
I merged in https://github.com/cburlacu/patchwork/tree/apitoken-dmg branch and this is the commit:
https://github.com/cburlacu/patchwork/commit/ca154fc1684e6fe26b3c04430f422dc81e12ce0d

**Comment by cburlacu** [comment]
Here you have pep8 warnings fixed 
https://github.com/cburlacu/patchwork/tree/apitoken-gciubotaru

**Comment by dlespiau** [comment]
Would you mind creating a real pull request rather than a branch? This way I can get travis to test it. Thanks.

**Comment by cburlacu** [comment]
done

**Comment by dlespiau** [comment]
Closing that one in favour of the new pull request from Cezar. https://github.com/dlespiau/patchwork/pull/170

**Comment by dlespiau** [comment]
For the problems with the HTTP errors: The URL hard codes the token ID ('tokens/1/'), but mysql doesn't reuse IDs when across test (ie the ID of the token increments as we run the tests).

In this case, I think you should be able to reuse the user1_at1 and user1_at2  'id' field in the query URL instead of always using '1'.

Now for the timestamps. The are two possible problems: we don't serialize the full precise timestamp in the JSON response, so when comparing it back to the local timestamp, it's truncated. MySQL also doesn't store the microseconds by default anyway. We don't really care about that amount of precision in this particular field. Truncating both timestamps to second precision before the comparison sounds like an acceptable trade off in the tests to me.

**Pull request closed without merging**
